title: Nordic RSE

description: >
    We bring together the community of people writing and contributing to
    research software from Nordic universities, research institutes, companies and
    other organizations to share knowledge, to organize meetings, and raise
    awareness for the scientific recognition of research software.

theme: minima

plugins:
  - jekyll-redirect-from

# https://github.com/jekyll/jekyll/issues/302
permalink: pretty
defaults:
  -
    scope:
      type: "pages"
    values:
      permalink: /:path/:basename/

# Collections
collections:
  other-events:
    output: true
  nordic-events:
    output: true
