title: Nordic RSE

description: >
    We bring together the community of people writing and contributing to
    research software from Nordic universities, research institutes, companies and
    other organizations to share knowledge, to organize meetings, and raise
    awareness for the scientific recognition of research software.

theme: minima

# later we can have more pages
# header_pages:
#  - something.md
